import type { LessonReferenceFigure } from './lessons';

// Remote originals discovered with Firecrawl. Keep source-specific credits with each image.
export const additionalLessonFigures: (LessonReferenceFigure & {
  lessonId: string;
  section: number;
})[] = [
  {
    lessonId: 'chem-u7-l1',
    section: 2,
    title: 'Hess’s law as an energy-level map',
    src: 'https://openstax.org/apps/archive/20260604.144757/resources/c17b9860b32de24c4f8e608fccd9a9ca1a572e3c',
    source: 'https://openstax.org/books/chemistry-2e/pages/5-3-enthalpy',
    alt: 'Energy levels compare carbon oxidation directly to carbon dioxide with a two-step route through carbon monoxide.',
    prompt:
      'Add the two enthalpy changes along the indirect route. Explain why the total agrees with the direct route even though the intermediates and number of steps differ.',
    author: 'OpenStax / Rice University',
    license: 'CC BY-NC-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-nc-sa/4.0/',
  },
  {
    lessonId: 'chem-u8-l1',
    section: 3,
    title: 'Activation energy and reaction enthalpy',
    src: 'https://openstax.org/apps/archive/20260604.144757/resources/c6711e3ad1036181079d6a0018566d990f483003',
    source: 'https://openstax.org/books/chemistry-2e/pages/12-5-collision-theory',
    alt: 'Reaction-coordinate diagram marking reactant energy, product energy, an activated complex, and the activation barrier.',
    prompt:
      'Locate the forward activation energy and the overall enthalpy change separately. Explain why a reaction can release energy yet proceed slowly at room temperature.',
    author: 'OpenStax / Rice University',
    license: 'CC BY-NC-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-nc-sa/4.0/',
  },
  {
    lessonId: 'chem-u8-l1',
    section: 3,
    title: 'Temperature changes the energetic fraction',
    src: 'https://openstax.org/apps/archive/20260604.144757/resources/2f83ee59874e6d78a5a300039ab038fe34360ab1',
    source: 'https://openstax.org/books/chemistry-2e/pages/12-5-collision-theory',
    alt: 'Two molecular-energy distributions compare the fraction of molecules above an activation-energy threshold at different temperatures.',
    prompt:
      'Compare the areas beyond the activation-energy threshold, not just the heights of the peaks. Why can a modest temperature increase produce a much larger change in reaction rate?',
    author: 'OpenStax / Rice University',
    license: 'CC BY-NC-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-nc-sa/4.0/',
  },
  {
    lessonId: 'chem-u5-l1',
    section: 0,
    title: 'Catalysts and the equilibrium position',
    src: 'https://openstax.org/apps/archive/20260604.144757/resources/ad64a45ab4cfe2badd8d653dd9ca2871d5740245',
    source:
      'https://openstax.org/books/chemistry-2e/pages/13-3-shifting-equilibria-le-chateliers-principle',
    alt: 'Catalyzed and uncatalyzed reaction-energy profiles share reactant and product levels but have different activation barriers.',
    prompt:
      'Trace both forward and reverse reactions over the lower barrier. Explain why a catalyst helps a mixture reach equilibrium faster without changing the equilibrium constant.',
    author: 'OpenStax / Rice University',
    license: 'CC BY-NC-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-nc-sa/4.0/',
  },
  {
    lessonId: 'chem-u6-l1',
    section: 4,
    title: 'Strong and weak acid titration curves',
    src: 'https://openstax.org/apps/archive/20260604.144757/resources/b647aecc61b9c2ed0244b202498ed119a4ac4cd4',
    source: 'https://openstax.org/books/chemistry-2e/pages/14-7-acid-base-titrations',
    alt: 'Comparison of titration curves for strong and weak acids with changes in pH as base is added.',
    prompt:
      'Identify initial pH, the steep rise, and the equivalence region on each curve. Explain why equal equivalence volumes do not require equal pH values at equivalence.',
    author: 'OpenStax / Rice University',
    license: 'CC BY-NC-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-nc-sa/4.0/',
  },
  {
    lessonId: 'chem-u6-l1',
    section: 4,
    title: 'Matching indicators to the pH jump',
    src: 'https://openstax.org/apps/archive/20260604.144757/resources/620c6acfc027775e49197e1995601ce664fbe1a3',
    source: 'https://openstax.org/books/chemistry-2e/pages/14-7-acid-base-titrations',
    alt: 'Chart of acid-base indicator colors and the pH intervals over which each indicator changes color.',
    prompt:
      'Choose an indicator whose transition falls inside the steep portion of the relevant titration curve. Explain why the endpoint and equivalence point are related but distinct ideas.',
    author: 'OpenStax / Rice University',
    license: 'CC BY-NC-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-nc-sa/4.0/',
  },
  {
    lessonId: 'therm-u1-l1',
    section: 0,
    title: 'Choosing a thermodynamic system',
    src: 'https://openstax.org/apps/archive/20260604.144757/resources/6cd2e07b661642a30fbc32738039bd5d5d0ccf03',
    source:
      'https://openstax.org/books/university-physics-volume-2/pages/3-1-thermodynamic-systems',
    alt: 'A gas in a piston-cylinder illustrates a system boundary and interactions with its surroundings.',
    prompt:
      'Choose the gas as your system and identify which boundary can move. Describe what crosses the boundary during heating and compression, distinguishing energy transfer from matter transfer.',
    author: 'OpenStax / Rice University',
    license: 'CC BY-NC-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-nc-sa/4.0/',
  },
  {
    lessonId: 'therm-u7-l1',
    section: 1,
    title: 'Reconciling work sign conventions',
    src: 'https://openstax.org/apps/archive/20260604.144757/resources/322a80d16db11262f1c316317f3b5ca7e53ce0f9',
    source: 'https://openstax.org/books/chemistry-2e/pages/5-3-enthalpy',
    alt: 'System and surroundings exchange heat and work, with arrows indicating energy-transfer directions.',
    prompt:
      'This chemistry figure defines w as work done on the system: ΔU = q + w. Translate it to this lesson’s work-by convention, ΔU = Q − W, and explain why both give the same physical energy change.',
    author: 'OpenStax / Rice University',
    license: 'CC BY-NC-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-nc-sa/4.0/',
  },
  {
    lessonId: 'therm-u8-l1',
    section: 3,
    title: 'Free expansion and irreversibility',
    src: 'https://openstax.org/apps/archive/20260604.144757/resources/e7b2c51b69aabd2430989b9b70c958f1e8368480',
    source:
      'https://openstax.org/books/university-physics-volume-2/pages/4-1-reversible-and-irreversible-processes',
    alt: 'Removing a partition lets gas spread into an initially empty part of a container.',
    prompt:
      'Explain why free expansion into a vacuum involves no external pressure-volume work. For an insulated ideal gas, distinguish unchanged internal energy from increased entropy.',
    author: 'OpenStax / Rice University',
    license: 'CC BY-NC-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-nc-sa/4.0/',
  },
  {
    lessonId: 'gene-u5-l1',
    section: 1,
    title: 'Testing models of DNA replication',
    src: 'https://openstax.org/apps/archive/20260604.144757/resources/891cb2e6c3f1d6a238ad6b341415ad17e5e2cfe5',
    source: 'https://openstax.org/books/biology-2e/pages/14-3-basics-of-dna-replication',
    alt: 'Conservative, semiconservative, and dispersive models show different arrangements of old and newly synthesized DNA strands.',
    prompt:
      'Follow one original strand through successive replication rounds. Which model predicts one old strand paired with one new strand in every first-generation daughter molecule?',
    author: 'OpenStax / Rice University',
    license: 'CC BY-NC-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-nc-sa/4.0/',
  },
  {
    lessonId: 'gene-u6-l1',
    section: 1,
    title: 'The lac operon integrates two signals',
    src: 'https://openstax.org/apps/archive/20260604.144757/resources/9c31214f4a001146ca61c4111db8dfdacb485325',
    source: 'https://openstax.org/books/biology-2e/pages/16-2-prokaryotic-gene-regulation',
    alt: 'Lac operon diagrams compare repressor binding and CAP-cAMP regulation under different sugar conditions.',
    prompt:
      'Track the lactose signal and the glucose/cAMP signal separately. Explain why removing repression alone does not necessarily produce the strongest transcription.',
    author: 'OpenStax / Rice University',
    license: 'CC BY-NC-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-nc-sa/4.0/',
  },
  {
    lessonId: 'gene-u7-l1',
    section: 1,
    title: 'From allele counts to genotype frequencies',
    src: 'https://openstax.org/apps/archive/20260604.144757/resources/6b1ca5ec21f8b2963b3d393de78ee0bdc8ce3f73',
    source: 'https://openstax.org/books/biology-2e/pages/19-1-population-evolution',
    alt: 'A pea-plant population links allele counts, allele frequencies, and Hardy–Weinberg genotype proportions.',
    prompt:
      'Reconstruct p and q from the allele counts, then calculate p², 2pq, and q². State the assumptions needed before treating these predicted proportions as a comparison model.',
    author: 'OpenStax / Rice University',
    license: 'CC BY-NC-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-nc-sa/4.0/',
  },
  {
    lessonId: 'gene-u9-l1',
    section: 1,
    title: 'PCR is a repeated molecular cycle',
    src: 'https://openstax.org/apps/archive/20260604.144757/resources/5063cf05bb7d5435ef73bab6a3b0b65872e30e9e',
    source: 'https://openstax.org/books/biology-2e/pages/17-1-biotechnology',
    alt: 'PCR diagram follows DNA denaturation, primer annealing, and strand extension over repeated amplification cycles.',
    prompt:
      'Locate the role of the primers and the direction of strand extension. Explain why a negative control is needed even when the intended target amplifies successfully.',
    author: 'OpenStax / Rice University',
    license: 'CC BY-NC-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-nc-sa/4.0/',
  },
  {
    lessonId: 'gene-u9-l1',
    section: 2,
    title: 'Cloning with a plasmid vector',
    src: 'https://openstax.org/apps/archive/20260604.144757/resources/5acef6c92935df62a0ff3ed56e586c0463e6c008',
    source: 'https://openstax.org/books/biology-2e/pages/17-1-biotechnology',
    alt: 'A plasmid cloning workflow inserts a DNA fragment into a vector and introduces recombinant DNA into a host cell.',
    prompt:
      'Distinguish cutting, joining, transformation, and selection. Why does survival under selection alone fail to prove that the insert has the intended sequence and orientation?',
    author: 'OpenStax / Rice University',
    license: 'CC BY-NC-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-nc-sa/4.0/',
  },
  {
    lessonId: 'prot-u2-l1',
    section: 2,
    title: 'Ribosome sites organize translation',
    src: 'https://openstax.org/apps/archive/20260604.144757/resources/e509d44e4464bb32316d892e989af64df955eb4c',
    source: 'https://openstax.org/books/biology-2e/pages/15-5-ribosomes-and-protein-synthesis',
    alt: 'Ribosome diagram identifies the A, P, and E sites that organize transfer RNAs during translation.',
    prompt:
      'Follow a charged tRNA from arrival through peptide transfer and exit. Connect ribosome movement along the mRNA to growth of the protein from its amino to its carboxyl terminus.',
    author: 'OpenStax / Rice University',
    license: 'CC BY-NC-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-nc-sa/4.0/',
  },
  {
    lessonId: 'prot-u2-l1',
    section: 0,
    title: 'Translation elongation, step by step',
    src: 'https://openstax.org/apps/archive/20260604.144757/resources/c4f499818ba85c5f4a2affcdae63c147cdd7f03b',
    source: 'https://openstax.org/books/biology-2e/pages/15-5-ribosomes-and-protein-synthesis',
    alt: 'A sequence of ribosome diagrams follows codon recognition, peptide-bond formation, and translocation.',
    prompt:
      'Identify which molecule carries the growing peptide before and after bond formation. Explain why moving the ribosome by one codon preserves the reading frame.',
    author: 'OpenStax / Rice University',
    license: 'CC BY-NC-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-nc-sa/4.0/',
  },
  {
    lessonId: 'bot-u3-l1',
    section: 0,
    title: 'Roots and shoots form a connected body',
    src: 'https://openstax.org/apps/archive/20260604.144757/resources/45a27c0f0e841e70203290ee8ead4ed1eeeaec3d',
    source: 'https://openstax.org/books/biology-2e/pages/30-1-the-plant-body',
    alt: 'Labeled flowering-plant diagram separates root and shoot systems and identifies major organs.',
    prompt:
      'Trace a water molecule from a root to a leaf and an assimilated carbon compound from a leaf toward a growing root. Which organs are connected by both transport pathways?',
    author: 'OpenStax / Rice University',
    license: 'CC BY-NC-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-nc-sa/4.0/',
  },
  {
    lessonId: 'bot-u4-l1',
    section: 0,
    title: 'Water potential predicts direction',
    src: 'https://openstax.org/apps/archive/20260604.144757/resources/30397f7a75026d448da2f8a87bbc32412bc8b4e7',
    source:
      'https://openstax.org/books/biology-2e/pages/30-5-transport-of-water-and-solutes-in-plants',
    alt: 'Connected water columns illustrate how solute concentration and applied pressure affect water movement.',
    prompt:
      'Compare the effects of adding solute and applying positive pressure. Predict water movement from total water potential rather than from solute concentration alone.',
    author: 'OpenStax / Rice University',
    license: 'CC BY-NC-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-nc-sa/4.0/',
  },
  {
    lessonId: 'bot-u4-l1',
    section: 3,
    title: 'Xylem and phloem transport different materials',
    src: 'https://openstax.org/apps/archive/20260604.144757/resources/328680818e492e6a7171cbae39e3d751231cb263',
    source:
      'https://openstax.org/books/biology-2e/pages/30-5-transport-of-water-and-solutes-in-plants',
    alt: 'Plant diagram contrasts xylem water transport with phloem movement between sugar sources and sinks.',
    prompt:
      'Label a source and two possible sinks. Explain why phloem flow can differ between separate tubes while xylem transport is associated with the transpiration stream.',
    author: 'OpenStax / Rice University',
    license: 'CC BY-NC-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-nc-sa/4.0/',
  },
  {
    lessonId: 'exp-u4-l1',
    section: 3,
    title: 'Strength of association is not direction',
    src: 'https://openstax.org/apps/archive/20260604.144757/resources/eb4cff5863e10bca52404b4abfec4031654b4408',
    source: 'https://openstax.org/books/introductory-statistics-2e/pages/12-2-scatter-plots',
    alt: 'Two scatter plots compare stronger and weaker negative associations between measured variables.',
    prompt:
      'Both plots trend downward. Explain which shows more consistent association and why a correlation pattern alone does not establish a causal mechanism.',
    author: 'OpenStax / Rice University',
    license: 'CC BY-NC-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-nc-sa/4.0/',
  },
  {
    lessonId: 'exp-u5-l1',
    section: 3,
    title: 'An outlier changes the interpretation',
    src: 'https://openstax.org/apps/archive/20260604.144757/resources/226d68a32c32e693b9878c3622a8f9370a407371',
    source: 'https://openstax.org/books/introductory-statistics-2e/pages/12-2-scatter-plots',
    alt: 'Paired scatter plots show a positive trend with and without a point far from the other observations.',
    prompt:
      'Describe the trend before considering the unusual point. Propose a check of the measurement record, then explain why deleting the point requires evidence rather than inconvenience.',
    author: 'OpenStax / Rice University',
    license: 'CC BY-NC-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-nc-sa/4.0/',
  },
  {
    lessonId: 'circ-u7-l1',
    section: 2,
    title: 'Ammeters belong in the current path',
    src: 'https://openstax.org/apps/archive/20260604.144757/resources/0cfb1f821e9dc1b4aa0f187565743112c6f585d0',
    source:
      'https://openstax.org/books/university-physics-volume-2/pages/10-4-electrical-measuring-instruments',
    alt: 'Circuit diagrams compare current-meter placement within a circuit and show how an ammeter is connected.',
    prompt:
      'Trace the branch current through the ammeter. Explain how its low resistance affects the circuit and why placing it directly across a supply creates a dangerous measurement error.',
    author: 'OpenStax / Rice University',
    license: 'CC BY-NC-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-nc-sa/4.0/',
  },
  {
    lessonId: 'circ-u7-l1',
    section: 1,
    title: 'Voltmeters compare two nodes',
    src: 'https://openstax.org/apps/archive/20260604.144757/resources/10a8b563c016e4e01284a1a87a792e553f252bec',
    source:
      'https://openstax.org/books/university-physics-volume-2/pages/10-4-electrical-measuring-instruments',
    alt: 'Circuit diagrams show a voltmeter connected to compare potential difference across a circuit element.',
    prompt:
      'Identify the two nodes the meter compares. Explain why a high input resistance is desirable and why inserting the voltmeter in series changes the intended measurement.',
    author: 'OpenStax / Rice University',
    license: 'CC BY-NC-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-nc-sa/4.0/',
  },
  {
    lessonId: 'anat-u2-l2',
    section: 0,
    title: 'Lung lobes and the bronchial entry points',
    src: 'https://openstax.org/apps/archive/20260604.144757/resources/db017adf40b25ef3a09b04de55fd9ea9bd21015a',
    source: 'https://openstax.org/books/anatomy-and-physiology-2e/pages/22-2-the-lungs',
    alt: 'Labeled lung anatomy shows the right and left lungs, lobes, fissures, and structures at the hilum.',
    prompt:
      'Orient the diagram using the patient’s right and left. Compare lobe numbers, then trace the route by which an airway and pulmonary vessels enter a lung.',
    author: 'OpenStax / Rice University',
    license: 'CC BY-NC-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-nc-sa/4.0/',
  },
  {
    lessonId: 'anat-u2-l2',
    section: 2,
    title: 'Pleural layers and the chest wall',
    src: 'https://openstax.org/apps/archive/20260604.144757/resources/ab75c5732c0dd28d9862cebcc0ae5955d578f763',
    source: 'https://openstax.org/books/anatomy-and-physiology-2e/pages/22-2-the-lungs',
    alt: 'An enlarged chest-wall cross section identifies the pleural membranes and narrow pleural cavity surrounding the lung.',
    prompt:
      'Trace from the chest wall to alveolar tissue through both pleural layers. Explain how the fluid-filled interface helps couple lung expansion to movement of the thoracic wall.',
    author: 'OpenStax / Rice University',
    license: 'CC BY-NC-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-nc-sa/4.0/',
  },
  {
    lessonId: 'astro-u3-l1',
    section: 3,
    title: 'Reading a populated H–R diagram',
    src: 'https://openstax.org/apps/archive/20260604.144757/resources/dd3b626194347b820b300c0437928fdb31869efd',
    source: 'https://openstax.org/books/astronomy-2e/pages/18-4-the-h-r-diagram',
    alt: 'Hertzsprung–Russell diagram plots named stars by luminosity and decreasing surface temperature, showing main-sequence, giant, supergiant, and white-dwarf groups.',
    prompt:
      'Check the temperature-axis direction before comparing stars. Choose two stars with similar temperatures but different luminosities and use L ∝ R²T⁴ to explain their different radii.',
    author: 'OpenStax / Rice University',
    license: 'CC BY-NC-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-nc-sa/4.0/',
  },
  {
    lessonId: 'for-u7-l1',
    section: 0,
    title: 'What separated DNA fragments look like',
    src: 'https://openstax.org/apps/archive/20260604.144757/resources/3555fbfb5d60aac2f601b4e04e73054022bf2cb2',
    source: 'https://openstax.org/books/biology-2e/pages/17-1-biotechnology',
    alt: 'Photographs show DNA fragments separated into gel bands and a researcher viewing DNA profiles under ultraviolet light.',
    prompt:
      'Compare positions of bands across the lanes. These are general gel images, not a forensic STR case: explain why an actual STR comparison also needs locus labels, size standards, controls, and a sample model.',
    author:
      'OpenStax; James Jacob / Tompkins Cortland Community College; International Rice Research Institute',
    license: 'CC BY-NC-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-nc-sa/4.0/',
  },
  {
    lessonId: 'bot-u2-l1',
    section: 2,
    title: 'Plant tissues under the microscope',
    src: 'https://openstax.org/apps/archive/20260604.144757/resources/4c4f961dc5433f2a7565e85bde67b8b630c8ff68',
    source: 'https://openstax.org/books/biology-2e/pages/30-1-the-plant-body',
    alt: 'Plant cross-section micrograph labels dermal, ground, and vascular tissues, including xylem and phloem.',
    prompt:
      'Find each tissue system in the actual specimen. Explain how cell position and organization support a transport or protective function, and why staining color alone is not an identification rule.',
    author: 'OpenStax; modified from (biophotos)/Flickr; scale-bar data Matt Russell',
    license: 'CC BY-NC-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-nc-sa/4.0/',
  },
  {
    lessonId: 'anat-u8-l2',
    section: 1,
    title: 'Antibody architecture in three dimensions',
    src: 'https://cdn.rcsb.org/pdb101/motm/21/1igt.gif',
    source: 'https://pdb101.rcsb.org/motm/21',
    alt: 'Molecular illustration shows the two arms and stem of an antibody assembled from paired heavy and light chains.',
    prompt:
      'Locate the antigen-binding arms and distinguish their specificity from the functions of the constant region. Explain how one molecule can connect recognition with downstream immune activity.',
    author: 'David S. Goodsell / RCSB Protein Data Bank',
    license: 'CC BY 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/4.0/',
  },
  {
    lessonId: 'prot-u5-l1',
    section: 3,
    title: 'Different antibodies recognize different epitopes',
    src: 'https://cdn.rcsb.org/pdb101/motm/21/hyhel-overlap.gif',
    source: 'https://pdb101.rcsb.org/motm/21',
    alt: 'Structural illustration compares three antibody fragments binding to different sites on a lysozyme protein.',
    prompt:
      'Locate the different contact regions on the same antigen. Explain why a mutation at one epitope can affect one antibody without necessarily preventing all antibodies from recognizing that antigen.',
    author: 'David S. Goodsell / RCSB Protein Data Bank',
    license: 'CC BY 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/4.0/',
  },
  {
    lessonId: 'water-u1-l1',
    section: 2,
    title: 'Carbon moves between water, air, and living systems',
    src: 'https://www.noaa.gov/sites/default/files/styles/landscape_width_1275/public/legacy/image/2019/Jun/carbon_cycle.jpg?h=8158fd78&itok=x2-7uBMU',
    source: 'https://www.noaa.gov/education/resource-collections/climate/carbon-cycle',
    alt: 'Carbon-cycle diagram links atmospheric carbon, terrestrial organisms, ocean exchange, and longer-term stores.',
    prompt:
      'Trace one route from atmospheric carbon dioxide into aquatic biomass and back to the atmosphere. Explain which steps connect carbon cycling with dissolved oxygen consumption or production.',
    author: 'NOAA',
    license: 'NOAA educational reuse policy',
    licenseUrl: 'https://oceanservice.noaa.gov/disclaimer.html',
  },
  {
    lessonId: 'dyn-u7-l1',
    section: 0,
    title: 'Groundwater occupies connected pore spaces',
    src: 'https://d9-wret.s3.us-west-2.amazonaws.com/assets/palladium/production/s3fs-public/styles/full_width/public/thumbnails/image/wss-gw-how-groundwater-occurs-diagram.png?itok=k98eCzVx',
    source: 'https://www.usgs.gov/water-science-school/science/aquifers-and-groundwater',
    alt: 'Subsurface cross section and magnified pore spaces distinguish the unsaturated zone, water table, and saturated zone.',
    prompt:
      'Locate the water table and compare pore contents above and below it. Explain why porosity describes storage while permeability depends on how those spaces connect.',
    author: 'USGS Water Science School',
    license: 'Public domain',
    licenseUrl: 'https://www.usgs.gov/information-policies-and-instructions/copyrights-and-credits',
  },
  {
    lessonId: 'dyn-u1-l1',
    section: 0,
    title: 'The water cycle includes human pathways',
    src: 'https://d9-wret.s3.us-west-2.amazonaws.com/assets/palladium/production/s3fs-public/media/images/USGS_WaterCycle_English_ONLINE_20230302.png',
    source: 'https://www.usgs.gov/water-science-school/water-cycle-diagrams',
    alt: 'Water-cycle landscape identifies major stores and flows, including natural pathways and human water use.',
    prompt:
      'Choose a watershed boundary and identify three flows crossing it. Explain why pumping and water transfers belong in a water budget alongside precipitation, runoff, and evaporation.',
    author: 'USGS / Water Science School',
    license: 'Public domain',
    licenseUrl: 'https://www.usgs.gov/information-policies-and-instructions/copyrights-and-credits',
  },
  {
    lessonId: 'remote-u7-l1',
    section: 0,
    title: 'Electromagnetic wavelengths and observing windows',
    src: 'https://assets.science.nasa.gov/dynamicimage/assets/science/cds/learn/images/ems/EMS_Diagram_09172025.jpg?w=2500&h=1406&fit=clip&crop=faces%2Cfocalpoint',
    source: 'https://science.nasa.gov/ems/01_intro/',
    alt: 'Electromagnetic-spectrum chart compares wavelength, frequency, radiation types, and atmospheric transmission.',
    prompt:
      'Compare visible, thermal infrared, and microwave bands. Explain how wavelength and atmospheric transmission influence the choice of sensor for an Earth-observation question.',
    author: 'NASA Science',
    license: 'NASA educational media usage guidelines',
    licenseUrl: 'https://www.nasa.gov/nasa-brand-center/images-and-media/',
  },
  {
    lessonId: 'epi-u1-l1',
    section: 3,
    title: 'Natural history separates stages of disease',
    src: 'https://archive.cdc.gov/www_cdc_gov/csels/dsepd/ss1978/lesson1/section9_html_files/Figure1.18.jpg',
    source: 'https://archive.cdc.gov/www_cdc_gov/csels/dsepd/ss1978/lesson1/section9.html',
    alt: 'Timeline distinguishes exposure, subclinical disease, symptom onset, and eventual outcomes.',
    prompt:
      'Place screening and symptom-based detection on different parts of the timeline. Explain how an incubation period can separate the time of exposure from the time a case is recognized.',
    author: 'CDC, Principles of Epidemiology (educational archive)',
    license: 'Public domain; CDC content reuse policy',
    licenseUrl: 'https://www.cdc.gov/other/agencymaterials.html',
  },
  {
    lessonId: 'epi-u8-l1',
    section: 3,
    title: 'Interrupting the chain of infection',
    src: 'https://archive.cdc.gov/www_cdc_gov/csels/dsepd/ss1978/lesson1/section10_html_files/Figure1.19.jpg',
    source: 'https://archive.cdc.gov/www_cdc_gov/csels/dsepd/ss1978/lesson1/section10.html',
    alt: 'Chain-of-infection diagram links an agent, reservoir, exit route, transmission, entry route, and susceptible host.',
    prompt:
      'Choose two different links and propose an intervention at each. Explain why an intervention aimed at transmission can work without directly treating the pathogen inside an infected person.',
    author: 'CDC, Principles of Epidemiology (educational archive)',
    license: 'Public domain; CDC content reuse policy',
    licenseUrl: 'https://www.cdc.gov/other/agencymaterials.html',
  },
  {
    lessonId: 'code-u4-l1',
    section: 0,
    title: 'A repeating-key comparison: the Vigenère square',
    src: 'https://upload.wikimedia.org/wikipedia/commons/2/25/Vigen%C3%A8re_square.svg',
    source: 'https://commons.wikimedia.org/wiki/File:Vigen%C3%A8re_square.svg',
    alt: 'Vigenère square organizes 26 shifted alphabets into a table indexed by plaintext and key letters.',
    prompt:
      'Use two different key letters on the same plaintext letter and compare the outputs. This is a Vigenère comparison, not a Porta table: explain why carrying this table into a Porta problem would use the wrong cipher convention.',
    author: 'Benjamin D. Esham (bdesham)',
    license: 'Public domain',
    licenseUrl: 'https://commons.wikimedia.org/wiki/File:Vigen%C3%A8re_square.svg',
  },
  {
    lessonId: 'rock-u1-l1',
    section: 0,
    title: 'Rock types connect through geological processes',
    src: 'https://upload.wikimedia.org/wikipedia/commons/8/8c/Rock_cycle_diagram.png',
    source: 'https://commons.wikimedia.org/wiki/File:Rock_cycle_diagram.png',
    alt: 'Rock-cycle diagram connects igneous, sedimentary, and metamorphic materials through multiple geological processes.',
    prompt:
      'Trace two possible routes from an igneous rock to a sedimentary rock. Explain why the rock cycle is a network of possible processes rather than a single compulsory sequence.',
    author: 'Emily Haddad',
    license: 'CC BY 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/4.0/',
  },
  {
    lessonId: 'rock-u5-l1',
    section: 3,
    title: 'Bowen’s reaction series and cooling magma',
    src: 'https://upload.wikimedia.org/wikipedia/commons/7/7a/Bowen%27s_Reaction_Series.png',
    source: 'https://commons.wikimedia.org/wiki/File:Bowen%27s_Reaction_Series.png',
    alt: 'Bowen’s reaction series compares discontinuous mineral changes and continuous plagioclase composition during magma cooling.',
    prompt:
      'Read from higher to lower temperatures along both branches. Explain how removal of early crystals can alter the composition of the remaining liquid instead of merely making all minerals grow together.',
    author: 'Colivine',
    license: 'CC0 1.0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
  },
];
